In [1]:
from sklearn.datasets import load_iris

In [2]:
from sklearn.model_selection import train_test_split

In [4]:
X,y=load_iris(return_X_y=True)

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [11]:
from sklearn.naive_bayes import GaussianNB

In [12]:
gnb=GaussianNB()

In [13]:
gnb.fit(X_train,y_train)

GaussianNB()

In [14]:
X.shape,y.shape

((150, 4), (150,))

In [15]:
X_train.shape,y_train.shape

((100, 4), (100,))

In [16]:
X_test.shape,y_test.shape

((50, 4), (50,))

In [17]:
y_pred=gnb.predict(X_test)

In [18]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 1, 2])

In [19]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [20]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_pred,y_test))

[[16  0  0]
 [ 0 19  0]
 [ 0  2 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.90      1.00      0.95        19
           2       1.00      0.87      0.93        15

    accuracy                           0.96        50
   macro avg       0.97      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50

0.96


In [21]:
import seaborn as sns

In [22]:
df=sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [36]:
df.shape

(244, 7)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [24]:
X=df.drop(columns=['tip'])
y=df['tip']

In [38]:
from sklearn.preprocessing import OneHotEncoder

In [40]:
encoder=OneHotEncoder()
encoder

OneHotEncoder()

In [41]:
encoder.fit_transform(df[['sex','smoker','day','time']])

<244x10 sparse matrix of type '<class 'numpy.float64'>'
	with 976 stored elements in Compressed Sparse Row format>

In [42]:
encoder.fit_transform(df[['sex','smoker','day','time']]).toarray()

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]])

In [ ]:
encoded=

In [26]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [32]:
from sklearn.naive_bayes import MultinomialNB

In [33]:
Mnb=GaussianNB()

In [34]:
Mnb.fit(X_train,y_train)

ValueError: Unknown label type: (array([ 1.  ,  1.01,  1.1 ,  1.25,  1.32,  1.44,  1.45,  1.47,  1.48,
        1.5 ,  1.56,  1.63,  1.64,  1.66,  1.68,  1.71,  1.73,  1.75,
        1.76,  1.83,  1.97,  1.98,  2.  ,  2.01,  2.02,  2.03,  2.05,
        2.09,  2.18,  2.24,  2.3 ,  2.31,  2.34,  2.5 ,  2.54,  2.55,
        2.56,  2.6 ,  2.71,  2.72,  2.74,  2.75,  2.83,  2.88,  2.92,
        3.  ,  3.02,  3.06,  3.11,  3.14,  3.15,  3.18,  3.21,  3.23,
        3.25,  3.27,  3.31,  3.35,  3.39,  3.4 ,  3.41,  3.48,  3.5 ,
        3.55,  3.6 ,  3.71,  4.  ,  4.08,  4.19,  4.3 ,  4.34,  4.5 ,
        4.67,  4.73,  5.  ,  5.15,  5.16,  5.17,  5.85,  5.92,  6.  ,
        6.5 ,  6.7 ,  6.73,  7.58, 10.  ]),)