In [1]:
import pandas as pd

In [2]:
df= pd.DataFrame({'colors':['red','green','blue','green','blue','red']})
df

colors
0    red
1  green
2   blue
3  green
4   blue
5    red

In [3]:
from sklearn.preprocessing import OneHotEncoder

In [4]:
encoder=OneHotEncoder()

In [5]:
encoder.fit_transform(df[['colors']])

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [6]:
encoded=pd.DataFrame(encoder.fit_transform(df[['colors']]).toarray(),columns=encoder.get_feature_names_out())
encoded

colors_blue  colors_green  colors_red
0          0.0           0.0         1.0
1          0.0           1.0         0.0
2          1.0           0.0         0.0
3          0.0           1.0         0.0
4          1.0           0.0         0.0
5          0.0           0.0         1.0

In [7]:
pd.concat([df,encoded],axis=1)

colors  colors_blue  colors_green  colors_red
0    red          0.0           0.0         1.0
1  green          0.0           1.0         0.0
2   blue          1.0           0.0         0.0
3  green          0.0           1.0         0.0
4   blue          1.0           0.0         0.0
5    red          0.0           0.0         1.0

In [8]:
import seaborn as sns

In [9]:
df=sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [10]:
data=pd.DataFrame(df[['sex','smoker','day']])
data

sex smoker   day
0    Female     No   Sun
1      Male     No   Sun
2      Male     No   Sun
3      Male     No   Sun
4    Female     No   Sun
..      ...    ...   ...
239    Male     No   Sat
240  Female    Yes   Sat
241    Male    Yes   Sat
242    Male     No   Sat
243  Female     No  Thur

[244 rows x 3 columns]

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
encoder=OneHotEncoder()

In [13]:
encoder.fit_transform(data[['sex','smoker','day']])

<244x8 sparse matrix of type '<class 'numpy.float64'>'
	with 732 stored elements in Compressed Sparse Row format>

In [14]:
encoder.fit_transform(data[['sex','smoker','day']]).toarray()

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 1., ..., 1., 0., 0.],
       [1., 0., 1., ..., 0., 0., 1.]])

In [15]:
encoded=pd.DataFrame(encoder.fit_transform(data[['sex','smoker','day']]).toarray(),columns=encoder.get_feature_names_out())
encoded

sex_Female  sex_Male  smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  \
0           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
1           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
2           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
3           0.0       1.0        1.0         0.0      0.0      0.0      1.0   
4           1.0       0.0        1.0         0.0      0.0      0.0      1.0   
..          ...       ...        ...         ...      ...      ...      ...   
239         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
240         1.0       0.0        0.0         1.0      0.0      1.0      0.0   
241         0.0       1.0        0.0         1.0      0.0      1.0      0.0   
242         0.0       1.0        1.0         0.0      0.0      1.0      0.0   
243         1.0       0.0        1.0         0.0      0.0      0.0      0.0   

     day_Thur  
0         0.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0  
..        ...  
239       0.0  
240       0.0  
241       0.0  
242       0.0  
243       1.0  

[244 rows x 8 columns]

In [16]:
pd.concat([data,encoded],axis=1)

sex smoker   day  sex_Female  sex_Male  smoker_No  smoker_Yes  \
0    Female     No   Sun         1.0       0.0        1.0         0.0   
1      Male     No   Sun         0.0       1.0        1.0         0.0   
2      Male     No   Sun         0.0       1.0        1.0         0.0   
3      Male     No   Sun         0.0       1.0        1.0         0.0   
4    Female     No   Sun         1.0       0.0        1.0         0.0   
..      ...    ...   ...         ...       ...        ...         ...   
239    Male     No   Sat         0.0       1.0        1.0         0.0   
240  Female    Yes   Sat         1.0       0.0        0.0         1.0   
241    Male    Yes   Sat         0.0       1.0        0.0         1.0   
242    Male     No   Sat         0.0       1.0        1.0         0.0   
243  Female     No  Thur         1.0       0.0        1.0         0.0   

     day_Fri  day_Sat  day_Sun  day_Thur  
0        0.0      0.0      1.0       0.0  
1        0.0      0.0      1.0       0.0  
2        0.0      0.0      1.0       0.0  
3        0.0      0.0      1.0       0.0  
4        0.0      0.0      1.0       0.0  
..       ...      ...      ...       ...  
239      0.0      1.0      0.0       0.0  
240      0.0      1.0      0.0       0.0  
241      0.0      1.0      0.0       0.0  
242      0.0      1.0      0.0       0.0  
243      0.0      0.0      0.0       1.0  

[244 rows x 11 columns]

Label or Ordinal Encoding


In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
df= pd.DataFrame({'colors':['red','green','blue','green','blue','red']})
df

colors
0    red
1  green
2   blue
3  green
4   blue
5    red

In [19]:
encoder= LabelEncoder()

In [20]:
encoder.fit_transform(df['colors'])

array([2, 1, 0, 1, 0, 2])

Ordinal Encoding

In [21]:
from sklearn.preprocessing import OrdinalEncoder

In [22]:
df=pd.DataFrame({'size':['small','medium','large','medium','small','large']})
df

size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [23]:
# create an instance
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [24]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

Target Guided ordinal Encoding

In [25]:
df= pd.DataFrame({'city':['london','paris','newyork','germany','london','paris'],
                  'Price':[200,100,300,500,600,400]})
df

city  Price
0   london    200
1    paris    100
2  newyork    300
3  germany    500
4   london    600
5    paris    400

In [26]:
mean_price=df.groupby('city')['Price'].mean().to_dict()
mean_price

{'germany': 500.0, 'london': 400.0, 'newyork': 300.0, 'paris': 250.0}

In [27]:
df['city_encoded']=df['city'].map(mean_price)

In [28]:
df

city  Price  city_encoded
0   london    200         400.0
1    paris    100         250.0
2  newyork    300         300.0
3  germany    500         500.0
4   london    600         400.0
5    paris    400         250.0

In [29]:
data=sns.load_dataset('tips')
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [30]:
df=data[['total_bill','day']]
df

total_bill   day
0         16.99   Sun
1         10.34   Sun
2         21.01   Sun
3         23.68   Sun
4         24.59   Sun
..          ...   ...
239       29.03   Sat
240       27.18   Sat
241       22.67   Sat
242       17.82   Sat
243       18.78  Thur

[244 rows x 2 columns]

In [31]:
mean_bill=df.groupby('day')['total_bill'].mean().to_dict()
mean_bill

{'Thur': 17.682741935483868,
 'Fri': 17.15157894736842,
 'Sat': 20.44137931034483,
 'Sun': 21.41}

In [32]:
df['day_encoded']=df['day'].map(mean_bill)


C:\Users\ptt920460\AppData\Local\Temp\ipykernel_8828\2837479089.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['day_encoded']=df['day'].map(mean_bill)


In [33]:
df

total_bill   day day_encoded
0         16.99   Sun   21.410000
1         10.34   Sun   21.410000
2         21.01   Sun   21.410000
3         23.68   Sun   21.410000
4         24.59   Sun   21.410000
..          ...   ...         ...
239       29.03   Sat   20.441379
240       27.18   Sat   20.441379
241       22.67   Sat   20.441379
242       17.82   Sat   20.441379
243       18.78  Thur   17.682742

[244 rows x 3 columns]